version: '3.8'

services:
  # The Node.js Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: photoark-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - photoark_net

  # PostgreSQL Database with pgvector
  db:
    image: pgvector/pgvector:pg16
    container_name: photoark-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - photoark_net

  # MinIO: S3-compatible storage for local testing
  minio:
    image: minio/minio:latest
    container_name: photoark-minio
    restart: unless-stopped
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - photoark_net

volumes:
  postgres_data:
  minio_data:

networks:
  photoark_net:
    driver: bridge